import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { useState } from "react";
import { BsSearch } from "react-icons/bs";
import fotobackground from "../weather2/images/FotoWeather.jpg";
import styles from "../weather2/styles/style.module.css";

export default function Home() {
  const [city, setCity] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;
  // const url = `https://api.openweathermap.org/data/2.5/weather?q=dubai&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) => {
      setWeather(response.data);
      console.log(response.data);
    });
    setCity("");
    setLoading(false);
  };

  // ### Css pelo chat gpt ele faz certo mas vai comparando (ex: o form acho q tem um so dele)
  return (
    <div className={styles["background"]}>
      <Head>
        <title>Race Engineering</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Overlay  N faz nada  */}
      {/* <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/10 z-[1]" /> */}

      {/* Background image-->Fica de back do search mas so EM cima) */}
      {/* <Image
          src={fotobackground}
          // objectPosition="center" melhorou so um poquinho
          layout="fill"
          className={styles["bg-image"]} // Aplicar a classe CSS para a imagem de fundo
          alt="qualquercoisa.."
        /> */}

      {/* Background image UM OUTRO */}
      {/* <div className="container">
        <Image
          src={fotobackground}
          className={styles["image"]}
          alt="qualquercoisa.."
        />
      </div> */}

      {/*FORMULARIO DE BUSCA */}
      <div className={styles["search"]}>
        <form onSubmit={fetchWeather} className={styles["form"]}>
          <div>
            <input
              onChange={(e) => setCity(e.target.value)}
              type="text"
              placeholder="Buscar Cidade"
              className={styles["search-input"]} // Aplicar a classe CSS para a caixa de busca
            />
          </div>
          <button className={styles["search-button"]} onClick={fetchWeather}>
            {/* <BsSearch size={20} /> */}
            <BsSearch size={20} />
          </button>
        </form>
      </div>
      {/* Weather */}
    </div>
  );
}
