import Head from "next/head";
// import Image from "next/image";
import axios from "axios";
import { useState } from "react";
import { BsSearch } from "react-icons/bs";
import styles from "../weather3/styles/style.module.css";
import Weather from "../weather3/components/Weather";
import Spinner from "../weather3/components/Spinner";

export default function Home() {
  const [city, setCity] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) => {
      setWeather(response.data);
      // console.log(response.data);
    });
    setCity("");
    setLoading(false);
  };

  if (loading) {
    return <Spinner />;
  } else {
    return (
      <div className={styles["background"]}>
        <Head>
          <title>Race Engineering</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/*FORMULARIO DE BUSCA */}
        <div className={styles["search"]}>
          <form onSubmit={fetchWeather} className={styles["form"]}>
            <div>
              <input
                onChange={(e) => setCity(e.target.value)}
                type="text"
                placeholder="Buscar Cidade"
                className={styles["search-input"]} // Aplicar a classe CSS para a caixa de busca
              />
            </div>
            <button className={styles["search-button"]} onClick={fetchWeather}>
              <BsSearch size={20} />
            </button>
          </form>
        </div>

        {/* Weather */}
        {weather.main && <Weather data={weather} />}
      </div>
    );
  }
}
