import Head from 'next/head'
import styles from '../styles/CadastroUsuario.module.css'
import logo from "../imgs/costs_logo.png"
import Image from 'next/image'
export default function cadastroUsuario(){
    return(
        <div>
            <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>
              
              <div className={styles.logo}>
              <Image
              src={logo}
              alt="minha logo"
              />
              </div>

              <div>
              <h1 className={styles.titulo} >Cadastrar Usuario</h1>
              </div>

            <form className={styles.form}>
             
                <div>
                    <input type="text" placeholder='EMAIL' name='email'></input>
                </div>
                <br/>

                <div>
                    <input type="password" placeholder='SENHA' name='password'></input>
                </div>
                <br/>
                
                <div>
                <label htmlFor="usuarios">Tipo de Usuarios:</label>
                <select  name="usuarios" id="usuarios">
                    <option value="analista"> Analista</option>
                    <option value="mecanico"> Mecanico</option>
                    <option value="piloto" > Piloto</option>
                </select>
                </div>
                <br/>
                
              
                <div>
                <input type="submit" value='CRIAR CONTA'></input>
                {/* <input type="submit" placeholder='CRIAR CONTA'></input> */}
                <a href='#'><button className={styles.botao}>FAZER LOGIN</button> </a>
                </div>

     
      </form>
        </div>
    )
}