import Head from 'next/head'
import styles from '../styles/Cadastro.module.css'
import logo from "../imgs/costs_logo.png"
import Image from 'next/image'
export default function cadastroCircuito(){
    return(
        <div>
            <Head>
            <title>Cadastro Circuito</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>
              
              <div className={styles.logo}>
              <Image
              src={logo}
              alt="minha logo"
              />
              </div>

              <div>
              <h1 className={styles.titulo} >Cadastrar Circuito</h1>
              </div>

            <form className={styles.form} action="/add" method="POST">
             
                
                <div>
                <p>Circuito</p>
                <select  name="circuito" id="circuito">
                <option value="select"> Select</option>
                    <option value="circuito1"> Circuito1</option>
                    <option value="circuito2"> Circuito2</option>
                    <option value="circuito3" > Circuito3</option>
                </select>
                </div>
                <br/>

                <div>
                    <input type="number" placeholder='Numero de Voltas'></input>
                </div>
                <br/>
                <br/>

                
                {/* <div className={styles.teste}> */}
                <div>
                <input type="submit" value='Avançar'></input>
                </div>

     
      </form>
        </div>
    )
}