import Head from 'next/head'
import styles from '../styles/Cadastro.module.css'
// import logo from "../../img/costs_logo.png";
import logo from "../imgs/costs_logo.png"
import Image from 'next/image'
export default function cadastroCorrida(){
    return(
        <div>
            <Head>
            <title>Cadastro Corrida</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>
              
              <div className={styles.logo}>
              <Image
              src={logo}
              alt="minha logo"
              />
              </div>

              <div>
              <h1 className={styles.titulo} >Cadastrar Corrida</h1>
              </div>

            <form className={styles.form} action="/add" method="POST">
             
                
                <div>
                <p>Analista</p>
                <select  name="analistas" id="analistas">
                <option value="select"> Select</option>
                    <option value="analista1"> Analista1</option>
                    <option value="analista2"> Analista2</option>
                    <option value="analista3" > Analista3</option>
                </select>
                </div>
                <br/>

                <div>
                <p>Mecanico</p>
                {/* nos options o value deve ser os mecanicos cadastrados(por enquanto faz um mock) */}
                <select  name="mecanico" id="mecanico">
                <option value="select"> Select</option>
                    <option value="mecanico1"> Mecanico1</option>
                    <option value="mecanico2"> Mecanico2</option>
                    <option value="mecanico3" > Mecanico3</option>
                </select>
                </div>
                <br/>


                <div>
                <p>Corredores</p>
                {/* nos options o value deve ser os corredores cadastrados(por enquanto faz um mock) */}
                <select  name="corredores" id="corredores">
                <option value="select"> Select</option>
                    <option value="corredor1"> Corredor1</option>
                    <option value="corredor2"> Corredor2</option>
                    <option value="corredor3" > Corredor3</option>
                </select>
                </div>
                <br/>


                <div>
                <p>Times</p>
                <select  name="usuarios" id="usuarios">
                <option value="select"> Select</option>
                    <option value="time1"> Time1</option>
                    <option value="time2"> Time2</option>
                    <option value="time3" > Time3</option>
                </select>
                </div>
                <br/>


                <div>
                <p>Data e hora  Inicio</p>
                <input type="datetime-local"></input>
                </div>
                <br/>


                <div>
                <p>Data e hora Fim</p>
                <input type="datetime-local"></input>
                </div>
                <br/>

                
                
                <div>
                <input type="submit" value='Avançar'></input>
                </div>

     
      </form>
        </div>
    )
}