import Head from 'next/head'
import styles from '../styles/Cadastro.module.css'
import logo from "../imgs/costs_logo.png"
import Image from 'next/image'
export default function cadastroCorrida(){
    return(
        <div >
            <Head>
            <title>Cadastro Corrida</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
              
                
            <div className={styles.body}>  

              <div className={styles.logo}>
              <Image
              src={logo}
              alt="minha logo"
              />
              </div>

              

            <form className={styles.form} action="/races" method="POST">
                 
              <div>
                <h1 className={styles.titulo} >Cadastrar Corrida</h1>
              </div>
                
                <div>
                <p>Selecione o Analista :</p>
                <select   name="analistas" id="analistas" className={styles.selecionar} >
                <option value="select"> Select</option>
                    <option value="analista1"> Analista1</option>
                    <option value="analista2"> Analista2</option>
                    <option value="analista3" > Analista3</option>
                </select>
                </div>
                <br/>

                <div>
                <p>Selecione o Mecanico:</p>
                <select  name="mecanico" id="mecanico" required className={styles.selecionar} >
                <option value="select"> Select</option>
                    <option value="mecanico1"> Mecanico1</option>
                    <option value="mecanico2"> Mecanico2</option>
                    <option value="mecanico3" > Mecanico3</option>
                </select>
                </div>
                <br/>


                <div>
                <p>Selecione o Piloto : </p>
                <select  name="corredores" id="corredores" className={styles.selecionar}>
                <option value="select"> Select</option>
                    <option value="corredor1"> Corredor1</option>
                    <option value="corredor2"> Corredor2</option>
                    <option value="corredor3" > Corredor3</option>
                </select>
                </div>
                <br/>


                <div>
                <p>Selecione o Time :</p>
                <select  name="usuarios" id="usuarios" className={styles.selecionar}>
                <option value="select"> Select</option>
                    <option value="time1"> Time1</option>
                    <option value="time2"> Time2</option>
                    <option value="time3" > Time3</option>
                </select>
                </div>
                <br/>


                <div>
                <p>Data e hora  Inicio</p>
                <input  required type="datetime-local"></input>
                </div>
                <br/>


                <div>
                <p>Data e hora Fim</p>
                <input required type="datetime-local"></input>
                </div>
                <br/>

                
                
                <div>
                <input type="submit" value='Avançar' className={styles.botaoinput}></input>
                </div>

     
      </form>

      </div>
        </div>
    )
}