import { Inter } from 'next/font/google';
import Head from 'next/head';
import Image from 'next/image';
import NextLink from 'next/link';

import styles from '@/styles/Home.module.css';
import { Box, Link } from '@chakra-ui/react';

import LoginPage from './login';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box height="100vh" width="100%">
        <Box
          height="100%"
          width="100%"
          display="flex"
          justifyContent="center"
          alignItems="center"
        >
          <LoginPage />
        </Box>
      </Box>
    </>
  );
}
